apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cm1cbhk41-java-springboot
  janus-idp.io/tekton: cm1cbhk41-java-springboot
  backstage.io/kubernetes-id: cm1cbhk41-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cm1cbhk41-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
